apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas
    component: gateway
  name: gateway-public
  namespace: openfaas
spec:
  ports:
  - name: http
    port: 8080
    nodePort: 31112
    protocol: TCP
    targetPort: http
  selector:
    app: gateway
  type: NodePort
