    - name: Add openfaas chart repo
      kubernetes.core.helm_repository:
        name: openfaas
        repo_url: " https://github.com/groundnuty/faas-netes/"
        force_update: true

    - name: Generate namespaces.yml from template
      template:
        src: namespaces.j2
        dest: openfaas-namespaces.yml
        
    - name: Create openfaas namespaces
      kubernetes.core.k8s:
        state: present
        src: openfaas-namespaces.yml

    - name: Copy openfaas-values.yaml
      template:
        src: values.j2
        dest: openfaas-values.yaml

    - name: Get current working directory
      command: pwd
      register: pwd_output

    - name: Print current working directory
      debug:
        msg: "Current working directory: {{ pwd_output.stdout }}"

    - name: Deploy latest version of OpenFaaS
      kubernetes.core.helm:
        name: openfaas
        chart_ref: openfaas/openfaas
        release_namespace: "{{openfaas_namespace}}"
        values_files:
          - openfaas-values.yaml
        set_values:
          - value: generateBasicAuth=true

    - name: Copy openfaas-gateway-public.yaml
      template:
        src: openfaas-gateway-public.j2
        dest: openfaas-gateway-public.yaml

    - name: Create public gateway service
      kubernetes.core.k8s:
        state: present
        src: openfaas-gateway-public.yaml
