docs:
  docker: docker.onedata.org/onedata-documentation:ID-e6c014d056
  output-path: ./persistence/html/docs
gui:
  docker: docker.onedata.org/homepage:ID-6efba6d87a
  output-path: ./persistence/html
