docs:
  docker: docker.onedata.org/onedata-documentation:ID-f70c057ce1
  output-path: ./persistence/html/docs
gui:
  docker: docker.onedata.org/homepage:ID-6efba6d87a
  output-path: ./persistence/html
