docs:
  docker: docker.onedata.org/onedata-documentation:ID-6528bc37e9
  output-path: ./persistence/html/docs
gui:
  docker: docker.onedata.org/homepage:ID-6efba6d87a
  output-path: ./persistence/html
