docs:
  docker: docker.onedata.org/onedata-documentation:ID-a3316ffcb7
  output-path: ./persistence/html/docs
gui:
  docker: docker.onedata.org/homepage:ID-6efba6d87a
  output-path: ./persistence/html
