docs:
  docker: docker.onedata.org/onedata-documentation:ID-ce07b46226
  output-path: ./persistence/html/docs
gui:
  docker: docker.onedata.org/homepage:ID-8f42c5e7b7
  output-path: ./persistence/html
