# Based on https://github.com/wmnnd/nginx-certbot
# LICENCE: https://github.com/wmnnd/nginx-certbot/blob/master/LICENSE

version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./config/nginx-preview.conf:/etc/nginx/conf.d/app.conf:ro
      - ./persistence/html:/var/www/html
    ports:
      - "8080:8080"
