version: '2'

services:
  node1.onezone:
    restart: always
    image: docker.onedata.org/onezone:ID-a9753f663d
    hostname: node1.onezone.internal
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: onezone
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      # Onezone persistence
      - "./data/persistence:/volumes/persistence"
      # Onezone config
      - "./data/configs/overlay.config:/etc/oz_worker/overlay.config"
      # OpenID & SAML config
      - "./data/secret/auth.config:/etc/oz_worker/auth.config"
      - "./data/images/eoscpl.svg:/var/www/html/oz_worker/custom/eoscpl.svg"

    ports:
      - "53:53"
      - "53:53/udp"
      - "80:80"
      - "443:443"
      - "9443:9443"
    stop_grace_period: 60m
    environment:
      #ONEPANEL_DEBUG_MODE: "true" # prevents container exit on configuration error
      ONEPANEL_BATCH_MODE: "true"
      ONEPANEL_LOG_LEVEL: "info" # prints logs to stdout (possible values: none, debug, info, error), by default set to info
      ONEPANEL_EMERGENCY_PASSPHRASE: ${EMERGENCY_PASSPHRASE}
      # Used for test purposes, disable when you have your own web cert mounted via volumes.
      # Cert will be generated only if none is found under cert path.

      # If enabled, a new web cert will be generated with CN matching the
      #   ONEPANEL_GENERATED_CERT_DOMAIN and signed by OnedataTestWebServerCa
      # NOTE: The generation will be performed upon every startup, any
      #   existing certs will be backed up and placed in the same directory.
      # WARNING: This feature is devised for test purposes and must not
      #   be used in production.
      ONEPANEL_GENERATE_TEST_WEB_CERT: "false"  # default: false
      # The generated test web cert will be issued for below domain.
      ONEPANEL_GENERATED_CERT_DOMAIN: ""  # default: ""
      # If enabled, onepanel will trust any server that has a cert signed by
      #   the OnedataTestWebServerCa.
      # WARNING: This feature is devised for test purposes and must not
      #   be used in production.
      ONEPANEL_TRUST_TEST_CA: "false"  # default: false

      ONEZONE_CONFIG: |
        cluster:
          domainName: "onezone.internal"
          nodes:
            n1:
              hostname: "node1"
          managers:
            mainNode: "n1"
            nodes:
              - "n1"
          workers:
            nodes:
              - "n1"
          databases:
            nodes:
              - "n1"
        onezone:
          name: "eosc pl"
          domainName: "data.eosc.pl"
          letsEncryptEnabled: false
