    # - name: Add openfaas chart repo
    #   kubernetes.core.helm_repository:
    #     name: openfaas
    #     repo_url: " https://openfaas.github.io/faas-netes/"
    #     force_update: true

    # - name: Create openfaas namespaces
    #   kubernetes.core.k8s:
    #     state: present
    #     src: https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml

    - name: Create onedata namespace
      kubernetes.core.k8s:
        name: onedata
        api_version: v1
        kind: Namespace
        state: present

    - name: Copy openfaas-pod-status-monitor charts
      copy:
        src: openfaas-pod-status-monitor.tgz
        dest: openfaas-pod-status-monitor.tgz

    - name: Unpack openfaas-pod-status-monitor.tgz
      shell: tar zxf openfaas-pod-status-monitor.tgz

    - name: Generate values.yaml
      template:
        src: values.j2
        dest: openfaas-pod-status-monitor-values.yaml


    # - name: Print current working directory
    #   debug:
    #     msg: "Current working directory: {{ pwd_output.stdout }}"

    - name: Deploy openfaas-pod-status-monitor
      kubernetes.core.helm:
        name: openfaas-pod-status-monitor
        chart_ref: ./openfaas-pod-status-monitor
        release_namespace: onedata
        values_files:
          - openfaas-pod-status-monitor-values.yaml
    #     set_values:
    #       - value: generateBasicAuth=true
    #     # values: 
    #     #   replicas: 2
